name: Build CSS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run build:css
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: generate compiled Tailwind CSS"
          file_pattern: assets/site.css
