name: Build CSS
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          # ⛔ removed "cache: 'npm'" to avoid lockfile requirement

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build Tailwind
        run: npm run build:css

      - name: Commit compiled CSS
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: generate compiled Tailwind CSS"
          file_pattern: assets/site.css
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
